sonar.projectKey=aero-vigil
sonar.working.directory=C:\\Projects\\aero-vigil\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Projects\\aero-vigil
sonar.pullrequest.cache.basepath=C:\\Projects\\aero-vigil

3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.projectKey=aero-vigil:3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C
3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.projectName=aero-vigil
3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.projectBaseDir=C:\\Projects\\aero-vigil
3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.sourceEncoding=utf-8
3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.tests=
3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.sources=\
"C:\\Projects\\aero-vigil\\FlightUtil.cs",\
"C:\\Projects\\aero-vigil\\InvalidFlightException.cs",\
"C:\\Projects\\aero-vigil\\User.cs",\
"C:\\Projects\\aero-vigil\\obj\\aero-vigil.csproj.nuget.dgspec.json",\
"C:\\Projects\\aero-vigil\\obj\\project.assets.json",\
"C:\\Projects\\aero-vigil\\bin\\Debug\\net10.0\\aero-vigil.deps.json",\
"C:\\Projects\\aero-vigil\\bin\\Debug\\net10.0\\aero-vigil.runtimeconfig.json"

3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.cs.analyzer.projectOutPaths=\
"C:\\Projects\\aero-vigil\\.sonarqube\\out\\0"
3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.cs.roslyn.reportFilePaths=\
"C:\\Projects\\aero-vigil\\.sonarqube\\out\\0\\Issues.json"
3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.cs.scanner.telemetry=\
"C:\\Projects\\aero-vigil\\.sonarqube\\out\\0\\Telemetry.json"

3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C.sonar.working.directory=C:\\Projects\\aero-vigil\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=3DFF9A97-8DDC-4E10-AFDB-540BD4745B3C

